# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TSTCalc
                                 A QGIS plugin
 Calculates true stratigraphic thickness between two points
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-22
        copyright            : (C) 2024 by Your Name
        email                : your.email@example.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

def classFactory(iface):
    """Load TSTCalc class from file TSTCalc.
    
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .tst_calc import TSTCalc
    return TSTCalc(iface)
